---
###
repository_gpg_key: '{{ ("https://" if repository_url | regex_search("^http(|s):\/\/") is none else "")
                        + repository_url
                        + "/zabbix-official-repo.key" }}'
repository_baseurl: '{{ ("https://" if repository_url | regex_search("^http(|s):\/\/") is none else "")
                    + repository_url + "/zabbix/"
                    + repository_version | string + "/"
                    + ansible_distribution | lower
                    + ("-arm64" if ansible_architecture == "aarch64" else "") }}'
# repository_url_old_agent2_plugins: '{{ repository_url + "/zabbixa_agent2_plugins/1/"
#           + ansible_distribution | lower
#           + ("-arm64" if ansible_architecture == "aarch64" else "") }}'
