---
agent_repository:
  name: 'zabbix-release'
  uri: '{{ agent_repository_mirror + "/zabbix/" + agent_major_version | string + "/"
          + ansible_distribution | lower
          + ("-arm64" if ansible_architecture == "aarch64" else "")
          + "/pool/main/z/zabbix-release/zabbix-release_latest"
          + "%2B" + ansible_distribution | lower + ansible_distribution_major_version
          + (".04" if ansible_distribution | lower == "ubuntu" else "")
          + "_all.deb" }}'

agent_package_list:
  - zabbix-sender
  - zabbix-get
  - 'zabbix-agent{{ "2" if agent_variant | string == "2" else "" }}'
