---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Include all from vars folder
      ansible.builtin.include_vars:
        dir: vars
        ignore_unknown_extensions: true
        extensions:
          - 'yaml'
          - 'yml'
      tags: [always]
  roles:
    - role: repository
    #    - role: agent
    #      tags: [agent]
    #    - role: host
    #      tags: [never, host]
    #      host_zabbix_api_port: 8070
