---
- name: Side Effect
  hosts: all
  tasks:
    - name: 'Side-Effect : APT : Previous repo zabbix-release'
      when: ansible_os_family == "Debian"
      become: true
      ansible.builtin.apt:
        # deb module requires xz-utils to be installed on target machine????
        deb: '{{ zabbix_repo_uri }}'
      environment:
        http_proxy: "{{ http_proxy | default(None) | default(omit) }}"
        https_proxy: "{{ https_proxy | default(None) | default(omit) }}"
      vars:
        zabbix_repo_uri: '{{ "https://repo.zabbix.com" + "/zabbix/" + repository_version | string + "/"
                + ansible_distribution | lower
                + ("-arm64" if ansible_architecture == "aarch64" else "")
                + "/pool/main/z/zabbix-release/zabbix-release_latest"
                + "%2B" + ansible_distribution | lower + ansible_distribution_major_version
                + (".04" if ansible_distribution | lower == "ubuntu" else "")
                + "_all.deb" }}'

    - name: 'Side-Effect : YUM : GPG key presence'
      when: ansible_os_family == "RedHat"
      become: true
      ansible.builtin.rpm_key:
        state: 'present'
        key: '{{ zabbix_repo_key }}'
      vars:
        zabbix_repo_key: '{{ map_gpg_key[map_os_transition[ansible_distribution][ansible_distribution_major_version]]
                 if map_os_transition[ansible_distribution][ansible_distribution_major_version] is defined
                   else map_gpg_key[ansible_distribution_major_version] }}'
      environment:
        http_proxy: '{{ http_proxy | default(None) | default(omit) }}'
        https_proxy: '{{ https_proxy | default(None) | default(omit) }}'
      tags: [deploy]

    - name: 'Side-Effect : YUM : Zabbix-release repository presence'
      become: true
      when: ansible_os_family == "RedHat"
      ansible.builtin.yum:
        name: '{{ zabbix_repo_uri }}'
      vars:
        zabbix_repo_uri: '{{ "https://repo.zabbix.com" + "/zabbix/" + repository_version | string + "/rhel/"
                + (map_os_transition[ansible_distribution][ansible_distribution_major_version] | string
                  if map_os_transition[ansible_distribution][ansible_distribution_major_version] is defined
                    else ansible_distribution_major_version | string)
                + "/" + ansible_architecture + "/zabbix-release-latest.el"
                + (map_os_transition[ansible_distribution][ansible_distribution_major_version] | string
                  if map_os_transition[ansible_distribution][ansible_distribution_major_version] is defined
                    else ansible_distribution_major_version | string)
          + ".noarch.rpm" }}'
      environment:
        http_proxy: '{{ http_proxy | default(None) | default(omit) }}'
        https_proxy: '{{ https_proxy | default(None) | default(omit) }}'
      tags: [deploy]
  vars:
    map_os_transition:
      RedHat:
        '6': '6'
        '7': '7'
        '8': '8'
        '9': '9'
      OracleLinux:
        '6': '6'
        '7': '7'
        '8': '8'
        '9': '9'
      CentOS:
        '6': '6'
        '7': '7'
        '8': '8'
        '9': '9'
      Rocky:
        '8': '8'
        '9': '9'
      AlmaLinux:
        '8': '8'
        '9': '9'
      Amazon:
        '2': '7'
        '2023': '9'
      Fedora:
        '19': '7'
        '20': '7'
        '21': '7'
        '22': '7'
        '23': '7'
        '24': '7'
        '25': '7'
        '26': '7'
        '27': '7'
        '28': '8'
        '29': '8'
        '30': '8'
        '31': '8'
        '32': '8'
        '33': '8'
        '34': '9'
        '35': '9'
        '36': '9'
        '37': '9'
        '38': '9'
        '39': '9'
    map_gpg_key:
      '7': 'http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591'
      '8': 'http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591'
      '9': 'http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-08EFA7DD'
