---
- name: 'APT : Zabbix-release repository presence'
  become: true
  until: repository_register_state is not failed
  retries: 3
  delay: 3
  register: repository_register_state
  ansible.builtin.apt:
    # deb module requires xz-utils to be installed on target machine????
    deb: '{{ zabbix_repo.uri }}'
  when: repository_state != "absent"
  environment:
    http_proxy: "{{ http_proxy | default(None) | default(omit) }}"
    https_proxy: "{{ https_proxy | default(None) | default(omit) }}"
