---
- name: 'DEBUG : Base info'
  ansible.builtin.debug:
    msg: >
      distr: {{ ansible_distribution }}
      major: {{ ansible_distribution_major_version }}
      become_method: {{ ansible_become_method }}
      map_os_transition: {{ map_os_transition }}
  tags: [never, debug]

- name: 'Assert : Supported OS'
  ansible.builtin.assert:
    that:
      - repository_supported_os is true
      - repository_major_version | string in ['6.0', '6.4'] #### External var pls!!!
    quiet: true
  vars:
    repository_supported_os: '{{
        map_supported_os_version[ansible_architecture][ansible_system][ansible_distribution] is defined
        and map_supported_os_version[ansible_architecture][ansible_system][ansible_distribution][ansible_distribution_major_version] is defined
        and ansible_distribution_version
          is regex(map_supported_os_version[ansible_architecture][ansible_system][ansible_distribution][ansible_distribution_major_version])
      }}'

- name: Include OS packager(yum/apt) specific tasks
  ansible.builtin.include_tasks: '{{ ansible_os_family | lower }}.yml'
