---
- name: 'YUM : GPG key presence'
  become: true
  ansible.builtin.rpm_key:
    state: '{{ repository_key_state }}'
    key: '{{ repository.key }}'
  vars:
    repository_key_state: '{{ "absent" if repository_state == "absent" else "present" }}'
  environment:
    http_proxy: '{{ http_proxy | default(None) | default(omit) }}'
    https_proxy: '{{ https_proxy | default(None) | default(omit) }}'

- name: 'YUM : Zabbix-release repository presence'
  become: true
  until: repository_register_state is not failed
  retries: 3
  delay: 3
  notify: 'YUM : yum clean all'
  ansible.builtin.yum:
    name: '{{ repository.uri }}'
  when: repository_state != "absent"
  register: repository_register_state
  environment:
    http_proxy: '{{ http_proxy | default(None) | default(omit) }}'
    https_proxy: '{{ https_proxy | default(None) | default(omit) }}'

- name: 'YUM : Set Zabbix repo priority'
  when: repository_priority and repository_priority is number
  become: true
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/zabbix.repo
    insertafter: '^\[zabbix\]'
    regexp: '^priority='
    line: 'priority={{ repository_priority | string }}'

### yum in rhel7(and earlier) requires "yum-plugin-priorities" packages installed and loaded
- name: 'YUM : Plugin "priorities" presence'
  when: >-
    repository_priority and repository_priority is number
    and map_os_transition[ansible_distribution] is defined
    and map_os_transition[ansible_distribution][ansible_distribution_major_version] is defined
    and map_os_transition[ansible_distribution][ansible_distribution_major_version] | int <= 7
  become: true
  until: repository_register_yum_plugin_presence is not failed
  retries: 3
  delay: 3
  register: repository_register_yum_plugin_presence
  ansible.builtin.yum:
    name: 'yum-plugin-priorities'
    state: '{{ repository_state }}'
