---
############################################################################################################################################
host_zabbix_api_server: localhost
host_zabbix_api_port: 8070
host_zabbix_api_user: Admin
host_zabbix_api_password: zabbix
# host_zabbix_api_token:05f6b2784a62034171f322c3938428b0dc465a2c43b4529e30eb8e0352b4f5d7
