---
- name: Converge 1
  hosts: all
  vars:
    agent_remove_previous_packages: true
    test_name: agentd
    agent_variant: 1
    report_path: '/tmp/playbook_verify_zabbix_agent.report'
  tasks:
    - name: "Testing role zabbix_agent: {{ test_name }}"
      ansible.builtin.include_role:
        name: "zabbix_agent"
      tags: [host, verify, report, test, vars, pause]

- name: Converge 2
  hosts: all
  gather_facts: false
  vars:
    # agent_remove_previous_packages: true
    test_name: agent2
    agent_variant: 2
    agent_param_listenport: 10020
    agent_param_userparameter: []
    report_path: '/tmp/playbook_verify_zabbix_agent.report'
  tasks:
    - name: Clear host errors
      ansible.builtin.meta: clear_host_errors
      tags: [host, verify, report, test, vars, pause]
    - name: "Testing role zabbix_agent: {{ test_name }}"
      ansible.builtin.include_role:
        name: "zabbix_agent"
      tags: [host, verify, report, test, vars, pause]

- name: Converge 3
  hosts: all
  gather_facts: false
  vars:
    # agent_remove_previous_packages: true
    test_name: agentd_psk
    agent_variant: 1
    agent_param_tlsconnect: unencrypted
    agent_param_tlsaccept:
      - psk
    agent_source_tlspskfile: 'files/.PSK/ZABBIX_AGENTD/{{ inventory_hostname }}'
    report_path: '/tmp/playbook_verify_zabbix_agent.report'
  tasks:
    - name: Clear host errors
      ansible.builtin.meta: clear_host_errors
      tags: [host, verify, report, test, vars, pause]
    - name: "Testing role zabbix_agent: {{ test_name }}"
      ansible.builtin.include_role:
        name: "zabbix_agent"
      tags: [host, verify, report, test, vars, pause]

- name: Converge 4
  hosts: all
  gather_facts: false
  vars:
    # agent_remove_previous_packages: true
    test_name: agent2_psk
    agent_variant: 2
    agent_param_listenport: 10020
    agent_param_tlsconnect: unencrypted
    agent_param_tlsaccept:
      - psk
    agent_param_userparameter: []
    agent_source_tlspskfile: 'files/.PSK/ZABBIX_AGENT2/{{ inventory_hostname }}'
    report_path: '/tmp/playbook_verify_zabbix_agent.report'
  tasks:
    - name: Clear host errors
      ansible.builtin.meta: clear_host_errors
      tags: [host, verify, report, test, vars, pause]
    - name: "Testing role zabbix_agent: {{ test_name }}"
      ansible.builtin.include_role:
        name: "zabbix_agent"
      tags: [host, verify, report, test, vars, pause]

- name: Converge 5
  hosts: all
  gather_facts: false
  vars:
    # agent_remove_previous_packages: true
    test_name: agentd_cert
    agent_variant: 1
    agent_param_tlsconnect: cert
    agent_param_tlsaccept:
      - cert
    agent_source_tlscafile: files/certs/ca.crt
    agent_source_tlscertfile: files/certs/{{ inventory_hostname }}.crt
    agent_source_tlskeyfile: files/certs/{{ inventory_hostname }}.key
    # agent_param_tlsservercertissuer: CN=root-ca
    # agent_param_tlsservercertsubject: CN=server
    report_path: '/tmp/playbook_verify_zabbix_agent.report'
  tasks:
    - name: Clear host errors
      ansible.builtin.meta: clear_host_errors
      tags: [host, verify, report, test, vars, pause]
    - name: "Testing role zabbix_agent: {{ test_name }}"
      ansible.builtin.include_role:
        name: "zabbix_agent"
      tags: [host, verify, report, test, vars, pause]

- name: Converge 6
  hosts: all
  gather_facts: false
  vars:
    # agent_remove_previous_packages: true
    test_name: agent2_cert
    agent_variant: 2
    agent_param_listenport: 10020
    agent_param_tlsconnect: cert
    agent_param_tlsaccept:
      - cert
    agent_source_tlscafile: files/certs/ca.crt
    agent_source_tlscertfile: files/certs/{{ inventory_hostname }}.crt
    agent_source_tlskeyfile: files/certs/{{ inventory_hostname }}.key
    # agent_param_tlsservercertissuer: CN=root-ca
    # agent_param_tlsservercertsubject: CN=server
    agent_param_userparameter: []
    report_path: '/tmp/playbook_verify_zabbix_agent.report'
  tasks:
    - name: Clear host errors
      ansible.builtin.meta: clear_host_errors
      tags: [host, verify, report, test, vars, pause]
    - name: "Testing role zabbix_agent: {{ test_name }}"
      ansible.builtin.include_role:
        name: "zabbix_agent"
      tags: [host, verify, report, test, vars, pause]

- name: Converge 7
  hosts: all
  vars:
    agent_remove_previous_packages: true
    test_name: agentd_custom
    agent_variant: 1
    agent_service_$1 bobr
    agent_service_$1 kobra
    agent_service_$1 1115
    agent_service_$1 1115
    report_path: '/tmp/playbook_verify_zabbix_agent.report'
  tasks:
    - name: Clear host errors
      ansible.builtin.meta: clear_host_errors
      tags: [host, verify, report, test, vars, pause]
    - name: "Testing role zabbix_agent: {{ test_name }}"
      ansible.builtin.include_role:
        name: "zabbix_agent"
      tags: [host, verify, report, test, vars, pause]

- name: Converge 8
  hosts: all
  gather_facts: false
  vars:
    # agent_remove_previous_packages: true
    test_name: agent2_custom
    agent_variant: 2
    agent_service_$1 bobr
    agent_service_$1 kobra
    agent_service_$1 1115
    agent_service_$1 1115
    agent_param_listenport: 10020
    agent_param_userparameter: []
    report_path: '/tmp/playbook_verify_zabbix_agent.report'
  tasks:
    - name: Clear host errors
      ansible.builtin.meta: clear_host_errors
      tags: [host, verify, report, test, vars, pause]
    - name: "Testing role zabbix_agent: {{ test_name }}"
      ansible.builtin.include_role:
        name: "zabbix_agent"
      tags: [host, verify, report, test, vars, pause]

- name: Converge 9
  hosts: all
  gather_facts: false
  vars:
    # agent_remove_previous_packages: true
    test_name: agentd_psk_custom
    agent_variant: 1
    agent_service_$1 bobr
    agent_service_$1 kobra
    agent_service_$1 1115
    agent_service_$1 1115
    agent_param_tlsconnect: unencrypted
    agent_param_tlsaccept:
      - psk
    agent_source_tlspskfile: 'files/.PSK/ZABBIX_AGENTD/{{ inventory_hostname }}'
    report_path: '/tmp/playbook_verify_zabbix_agent.report'
  tasks:
    - name: Clear host errors
      ansible.builtin.meta: clear_host_errors
      tags: [host, verify, report, test, vars, pause]
    - name: "Testing role zabbix_agent: {{ test_name }}"
      ansible.builtin.include_role:
        name: "zabbix_agent"
      tags: [host, verify, report, test, vars, pause]

- name: Converge 10
  hosts: all
  gather_facts: false
  vars:
    # agent_remove_previous_packages: true
    test_name: agent2_psk_custom
    agent_variant: 2
    agent_service_$1 bobr
    agent_service_$1 kobra
    agent_service_$1 1115
    agent_service_$1 1115
    agent_param_listenport: 10020
    agent_param_tlsconnect: unencrypted
    agent_param_tlsaccept:
      - psk
    agent_param_userparameter: []
    agent_source_tlspskfile: 'files/.PSK/ZABBIX_AGENT2/{{ inventory_hostname }}'
    report_path: '/tmp/playbook_verify_zabbix_agent.report'
  tasks:
    - name: Clear host errors
      ansible.builtin.meta: clear_host_errors
      tags: [host, verify, report, test, vars, pause]
    - name: "Testing role zabbix_agent: {{ test_name }}"
      ansible.builtin.include_role:
        name: "zabbix_agent"
      tags: [host, verify, report, test, vars, pause]

- name: Converge 11
  hosts: all
  gather_facts: false
  vars:
    # agent_remove_previous_packages: true
    test_name: agentd_cert_custom
    agent_variant: 1
    agent_service_$1 bobr
    agent_service_$1 kobra
    agent_service_$1 1115
    agent_service_$1 1115
    agent_param_tlsconnect: cert
    agent_param_tlsaccept:
      - cert
    agent_source_tlscafile: files/certs/ca.crt
    agent_source_tlscertfile: files/certs/{{ inventory_hostname }}.crt
    agent_source_tlskeyfile: files/certs/{{ inventory_hostname }}.key
    # agent_param_tlsservercertissuer: CN=root-ca
    # agent_param_tlsservercertsubject: CN=server
    report_path: '/tmp/playbook_verify_zabbix_agent.report'
  tasks:
    - name: Clear host errors
      ansible.builtin.meta: clear_host_errors
      tags: [host, verify, report, test, vars, pause]
    - name: "Testing role zabbix_agent: {{ test_name }}"
      ansible.builtin.include_role:
        name: "zabbix_agent"
      tags: [host, verify, report, test, vars, pause]

- name: Converge 12
  hosts: all
  gather_facts: false
  vars:
    # agent_remove_previous_packages: true
    test_name: agent2_cert_custom
    agent_variant: 2
    agent_service_$1 bobr
    agent_service_$1 kobra
    agent_service_$1 1115
    agent_service_$1 1115
    agent_param_listenport: 10020
    agent_param_tlsconnect: cert
    agent_param_tlsaccept:
      - cert
    agent_source_tlscafile: files/certs/ca.crt
    agent_source_tlscertfile: files/certs/{{ inventory_hostname }}.crt
    agent_source_tlskeyfile: files/certs/{{ inventory_hostname }}.key
    # agent_param_tlsservercertissuer: CN=root-ca
    # agent_param_tlsservercertsubject: CN=server
    agent_param_userparameter: []
    report_path: '/tmp/playbook_verify_zabbix_agent.report'
  tasks:
    - name: Clear host errors
      ansible.builtin.meta: clear_host_errors
      tags: [host, verify, report, test, vars, pause]
    - name: "Testing role zabbix_agent: {{ test_name }}"
      ansible.builtin.include_role:
        name: "zabbix_agent"
      tags: [host, verify, report, test, vars, pause]
