- name: SE test
  hosts: all
  roles:
    - role: agent
      agent_package_state: latest
      agent_variant: 2
      agent_param_listenport: 10050
      agent_major_version: 6.0
      agent_apply_seport: true
      agent_apply_semodule: true
      agent_seboolean_zabbix_run_sudo: "on"
