- name: Reload
  hosts: all
  roles:
    - role: agent
      #######################################
      # agent_remove_previous_packages: true
      agent_verify_report_path: '/tmp/examples_verify_zabbix_agent.report'
      agent_test_name: '{{ ansible_play_name }}'
      #######################################
      agent_major_version: 6.4
      agent_param_server: ::/0              # address of Zabbix server to accept connections from;
      agent_param_serveractive: 192.168.64.1   # address of Zabbix server to connect using active checks;
      agent_param_hostmetadata: '{{ group_names | join(",") }}'   # concatenate group list to the string;
      agent_param_userparameter:
        - testreload, pwd
        - testreload2, pwd
