### Extract cert data for host: requires openssl installation on
- name: 'Prepare certificate data'
  when: >-
    (param_tlsconnect == "cert" or "cert" in param_tlsaccept)
    and source_tlscertfile is defined
    and zabbix_host_get_cert_info is defined and zabbix_host_get_cert_info
  tags: [host]
  block:
    - name: Get certificate info
      delegate_to: localhost
      ansible.builtin.command: 'openssl x509 -in {{ source_tlscertfile }} -noout --subject --issuer'
      # local_action: ansible.builtin.command openssl x509 -in {{ source_tlscertfile }} -noout --subject --issuer
      changed_when: false
      register: zabbix_agent_cert_data
    - name: 'SET FACT : Certificate issuer and subject'
      ansible.builtin.set_fact:
        zabbix_host_tls_issuer: '{{ zabbix_agent_cert_data.stdout | regex_search("issuer=(.*)$", "\1", multiline=True) | first | replace(" ", "") }}'
        zabbix_host_tls_subject: '{{ zabbix_agent_cert_data.stdout | regex_search("subject=(.*)$", "\1", multiline=True) | first | replace(" ", "") }}'

### Compone list of unique hostgroup names from all hosts, that reached this taks without failures.
- name: 'Prepare hostgroups block'
  when: >-
    "host" in ansible_run_tags
    or run_host_tasks is defined and run_host_tasks
  delegate_to: 'localhost'
  tags: [host]
  block:
    - name: 'SET FACT : Populate "hostvars" magic variable with zabbix_host_hostgroups'
      ansible.builtin.set_fact:
        zabbix_host_hostgroups: '{{ zabbix_host_hostgroups }}'
    - name: 'SET FACT : prepare list of hostgroups'
      when: >-
        "remove" not in ansible_run_tags
      delegate_to: localhost
      run_once: true
      ansible.builtin.set_fact:
        full_hostgroup_list: '{{
            ((full_hostgroup_list | default([])) + hostvars[item]["zabbix_host_hostgroups"]) | unique
          }}'
      loop: '{{ ansible_play_hosts }}'

### Add hostgroups and manage hosts using Zabbix API
- name: 'Zabbix API block'
  when: >-
    "host" in ansible_run_tags
    or "remove" in ansible_run_tags
    or run_host_tasks is defined and run_host_tasks
  delegate_to: '{{ zabbix_api_host }}'
  vars:
    ansible_connection: httpapi
    ansible_network_os: zabbix.zabbix.zabbix
    ansible_httpapi_port: '{{ zabbix_api_port }}'
    ansible_user: '{{ zabbix_api_user if zabbix_api_token is not defined else omit }}'
    ansible_httpapi_pass: '{{ zabbix_api_password if zabbix_api_token is not defined else omit }}'
    ansible_httpapi_use_ssl: '{{ zabbix_api_use_ssl | default("False") }}'
    ansible_httpapi_validate_certs: '{{ zabbix_api_validate_certs | default("False") }}'
  tags: [host, remove]
  block:
    - name: 'Zabbix API : Hostgroup presence'
      when: >-
        "remove" not in ansible_run_tags
        and zabbix_host_state == "present"
      run_once: true
      zabbix.zabbix.zabbix_hostgroup:
        name: '{{ full_hostgroup_list }}'
        state: present
    - name: 'Zabbix API : Host presence'
      throttle: 1
      zabbix.zabbix.zabbix_host:
        state: '{{ zabbix_host_state }}'
        host_name: '{{ zabbix_host_host_name }}'
        visible_name: '{{ zabbix_host_visible_name | default(omit) }}'
        description: '{{ zabbix_host_description | default(omit) }}'
        hostgroups: '{{ zabbix_host_hostgroups }}'
        templates: '{{ zabbix_host_templates | default(omit) }}'
        interfaces: '{{ zabbix_host_interfaces | default(omit) }}'
        tags: '{{ zabbix_host_tags | default(omit) }}'
        macros: '{{ zabbix_host_macros | default(omit) }}'
        inventory_mode: '{{ zabbix_host_inventory_mode | default(omit) }}'
        inventory: '{{ zabbix_host_inventory | default(omit) }}'
        status: '{{ zabbix_host_status | default(omit) }}'
        proxy: '{{ zabbix_host_proxy | default(None) }}'
        ### tls
        tls_accept: '{{ zabbix_host_tls_accept }}'
        tls_connect: '{{ zabbix_host_tls_connect }}'
        tls_psk_identity: '{{ zabbix_host_tls_psk_identity
          if "remove" not in ansible_run_tags
            and (zabbix_host_tls_connect == "psk" or "psk" in zabbix_host_tls_accept)
          else omit }}'
        tls_psk: '{{ zabbix_agent_psk_value
          if "remove" not in ansible_run_tags
            and (zabbix_host_tls_connect == "psk" or "psk" in zabbix_host_tls_accept)
          else omit }}'
        tls_issuer: '{{ zabbix_host_tls_issuer | default(omit) }}'
        tls_subject: '{{ zabbix_host_tls_subject | default(omit) }}'
        ### ipmi
        ipmi_authtype: '{{ zabbix_host_ipmi_authtype | default(omit) }}'
        ipmi_privilege: '{{ zabbix_host_ipmi_privilege | default(omit) }}'
        ipmi_username: '{{ zabbix_host_ipmi_username | default(omit) }}'
        ipmi_password: '{{ zabbix_host_ipmi_password | default(omit) }}'
