---
### Supported OS version map
##
## minor versions compared using regex: '.*' - any minor
repository_map_os_support:
  '6.0':
    x86_64:
      RedHat:
        '7': '.*'
        '8': '.*'
        '9': '.*'
      OracleLinux:
        '8': '.*'
        '9': '.*'
      AlmaLinux:
        '8': '.*'
        '9': '.*'
      Rocky:
        '8': '.*'
        '9': '.*'
      CentOS:
        '8': '.*'
        '9': '.*'
      Ubuntu:
        '18': '04'
        '20': '04'
        '22': '04'
      Debian:
        '9': '.*'
        '10': '.*'
        '11': '.*'
        '12': '.*'
    aarch64:
      Ubuntu:
        '20': '04'
        '22': '04'
      Debian:
        '12': '.*'
      RedHat:
        '8': '.*'
        '9': '.*'
      OracleLinux:
        '8': '.*'
        '9': '.*'
      AlmaLinux:
        '8': '.*'
        '9': '.*'
      Rocky:
        '8': '.*'
        '9': '.*'
      CentOS:
        '8': '.*'
        '9': '.*'
  '6.4':
    x86_64:
      RedHat:
        '7': '.*'
        '8': '.*'
        '9': '.*'
      OracleLinux:
        '8': '.*'
        '9': '.*'
      AlmaLinux:
        '8': '.*'
        '9': '.*'
      Rocky:
        '8': '.*'
        '9': '.*'
      CentOS:
        '8': '.*'
        '9': '.*'
      Ubuntu:
        '18': '04'
        '20': '04'
        '22': '04'
      Debian:
        '9': '.*'
        '10': '.*'
        '11': '.*'
        '12': '.*'
    aarch64:
      Ubuntu:
        '20': '04'
        '22': '04'
      RedHat:
        '8': '.*'
        '9': '.*'
      OracleLinux:
        '8': '.*'
        '9': '.*'
      AlmaLinux:
        '8': '.*'
        '9': '.*'
      Rocky:
        '8': '.*'
        '9': '.*'
      CentOS:
        '8': '.*'
        '9': '.*'
  '6.5':
    x86_64:
      RedHat:
        '7': '.*'
        '8': '.*'
        '9': '.*'
      OracleLinux:
        '8': '.*'
        '9': '.*'
      AlmaLinux:
        '8': '.*'
        '9': '.*'
      Rocky:
        '8': '.*'
        '9': '.*'
      CentOS:
        '8': '.*'
        '9': '.*'
      Ubuntu:
        '18': '04'
        '20': '04'
        '22': '04'
      Debian:
        '9': '.*'
        '10': '.*'
        '11': '.*'
        '12': '.*'
    aarch64:
      Ubuntu:
        '20': '04'
        '22': '04'
      Debian:
        '12': '.*'
      RedHat:
        '8': '.*'
        '9': '.*'
      OracleLinux:
        '8': '.*'
        '9': '.*'
      AlmaLinux:
        '8': '.*'
        '9': '.*'
      Rocky:
        '8': '.*'
        '9': '.*'
      CentOS:
        '8': '.*'
        '9': '.*'
