---
repository_map:
  Debian:
    name: 'zabbix-release'
    uri: '{{ repository_mirror + "/zabbix/" + repository_major_version | string + "/"
            + ansible_distribution | lower
            + ("-arm64" if ansible_architecture == "aarch64" else "")
            + "/pool/main/z/zabbix-release/zabbix-release_latest"
            + "%2B" + ansible_distribution | lower + ansible_distribution_major_version
            + (".04" if ansible_distribution | lower == "ubuntu" else "")
            + "_all.deb" }}'
  RedHat:
    # if version transition(fedora, amazon etc) is not available it will use default ansible_distribution_major_version mappings.
    name: 'zabbix'  # for enable/disable repo during package installation
    key: '{{ map_gpg_key[map_os_transition[ansible_distribution][ansible_distribution_major_version]]
             if map_os_transition[ansible_distribution][ansible_distribution_major_version] is defined
               else map_gpg_key[ansible_distribution_major_version] }}'
    uri: '{{ repository_mirror + "/zabbix/" + repository_major_version | string + "/rhel/"
            + (map_os_transition[ansible_distribution][ansible_distribution_major_version] | string
              if map_os_transition[ansible_distribution][ansible_distribution_major_version] is defined
                else ansible_distribution_major_version | string)
            + "/" + ansible_architecture + "/zabbix-release-latest.el"
            + (map_os_transition[ansible_distribution][ansible_distribution_major_version] | string
              if map_os_transition[ansible_distribution][ansible_distribution_major_version] is defined
                else ansible_distribution_major_version | string)
            + ".noarch.rpm" }}'