---
- name: Converge
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    #  pre_tasks:
    #    - name: python3-debian
    #      ansible.builtin.apt:
    #        name: python3-debian
    #        state: present
    #  pre_tasks:
    #    - name: Include all from vars folder
    #      ansible.builtin.include_vars:
    #        dir: vars
    #        ignore_unknown_extensions: true
    #        extensions:
    #          - 'yaml'
    #          - 'yml'
    #      tags: [always]
  roles:
    - role: repository
    #    - role: agent
    #      tags: [agent]
    #    - role: host
    #      tags: [never, host]
    #      host_zabbix_api_port: 8070
  post_tasks:
    - name: zabbix-agent
      ansible.builtin.apt:
        name:
          - python3-debian
          - zabbix-agent
        state: latest
        policy_rc_d: 101
        # update cache before installing
        cache_valid_time: 0
        update_cache: true
    - name: version
      ansible.builtin.command: zabbix_agentd -V
      register: agent_version
    - name: version output
      ansible.builtin.debug:
        msg: '{{ agent_version.stdout }}'
